In [1]:
 import numpy as np


In [3]:
arr1=np.arange(1000000)

In [5]:
arr1

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [7]:
arr3=np.random.rand(3,4)
arr3

array([[0.82561242, 0.0768564 , 0.4406564 , 0.91924738],
       [0.10439623, 0.44888904, 0.34449055, 0.94809996],
       [0.20182313, 0.94454905, 0.0054394 , 0.986704  ]])

In [9]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [15]:
l=[[1,2,3],[4,5,6]]
arr1=np.array(l)
arr1
arr1.shape[0]
arr1.dtype

dtype('int32')